### ISSUE TITLE
[Request] Flesh out "How to use" section

### ISSUE THREAD

**Issue by codeanpeace** [coleturner/react-timespan#1]
This looks neat looking at the gif!

Unfortunately I'm having some trouble getting this up and running. Any chance you could flesh out the "How to use" section and/or add an example react app? Thanks!

**Comment by TimNZ** [comment]
Hastily developed and published by the maker, and then forgotten.
Shame, it is a nice start.

```
import React from 'react'
import ReactDOM from 'react-dom'
import Timeline from 'react-timespan/dist/Timeline.js';
import 'react-timespan/stylesheet.scss'
const activities = [
  {
    name: 'Cole Turner',
    start: '1991-02-24',
    url: 'http://cole.codes/',
    body: 'As a baby I was born because something about birds and bees.'
  },
  {
    name: 'The Year I Wrote This',
    start: '2017-01-01',
    end: '2017-12-31',
    url: 'http://cole.codes/',
    body: 'Truly I made this for my portfolio and decided to sh are.'
  }
];

ReactDOM.render(<Timeline activities={activities} />,document.getElementById('app'))
```

**Comment by coleturner** [comment]
Seriously, the nerve of some maintainers - releasing free components and not writing a novel of documentation around it.

**Comment by coleturner** [comment]
All jokes aside, PRs are warmly welcomed. This is a component I built for a portfolio and subsequently replaced :)

**Comment by TimNZ** [comment]
I'm not entitled to anything, but I'm seriously considering trying to start a movement for a OSS code of practice MANDATING a live working demo and complete working example if you post a project onto Github and write a blog about it 😄
